# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1

shared: &shared
  steps:
    - checkout

    - run:
        name: Install dependencies
        command: |
          gem i bundler -v'> 2'
          bundle install --jobs=4 --retry=3

    - run:
        name: Run rubocop
        command: |
          bundle exec rubocop

    - run:
        name: Run tests
        command: |
          bundle exec rspec --color --require spec_helper spec --format progress

jobs:
  "ruby-23":
    <<: *shared
    docker:
      - image: circleci/ruby:2.3-node-browsers
        environment:
          BUNDLE_PATH: vendor/bundle
  "ruby-24":
    <<: *shared
    docker:
      - image: circleci/ruby:2.4-node-browsers
        environment:
          BUNDLE_PATH: vendor/bundle
  "ruby-25":
    <<: *shared
    docker:
      - image: circleci/ruby:2.5-node-browsers
        environment:
          BUNDLE_PATH: vendor/bundle
  "ruby-26":
    <<: *shared
    docker:
      - image: circleci/ruby:2.6-node-browsers
        environment:
          BUNDLE_PATH: vendor/bundle
  "jruby-91":
    <<: *shared
    docker:
      - image: circleci/jruby:9.1-jdk
        environment:
          BUNDLE_PATH: vendor/bundle
          JRUBY_OPTS: "--debug"
  "jruby-92":
    <<: *shared
    docker:
      - image: circleci/jruby:9.2-jdk
        environment:
          BUNDLE_PATH: vendor/bundle
          JRUBY_OPTS: "--debug"

workflows:
  version: 2
  build:
    jobs:
      - "ruby-23"
      - "ruby-24"
      - "ruby-25"
      - "ruby-26"
      - "jruby-91"
      - "jruby-92"
